### ISSUE TITLE
'module' object has no attribute 'PROTOCOL_SSLv3'

### ISSUE THREAD

**Issue by jermyk1** [threatstream/shockpot#8]
on ubuntu i get this error,
quick search on google showed they removed SSLv3 from python.
donno, any solution ?

# python shockpot.py 
Traceback (most recent call last):
  File "shockpot.py", line 9, in <module>
    from util import get_hpfeeds_client, get_ext_ip
  File "/home/kippo/shockpot-master/util.py", line 4, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 73, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

**Comment by jt6211** [comment]
Can you try this?

```
sudo su -
source /opt/shockpot/env/bin/activate
pip install requests==2.6.0
supervisorctl restart shockpot
```

Does this fix it?

ref: http://stackoverflow.com/questions/28987891/patch-pyopenssl-for-sslv3-issue

**Comment by jermyk1** [comment]
sorry, my fault, should have pay more attention,
ubuntu didnt had virtualenv, once i followed the instructions it worked :+1: 
apt-get install virtualenv
